### ISSUE TITLE
Upload Progress only called at end

### ISSUE THREAD

**Issue by pauloec** [filestack/filestack-swift#11]
Upload handler only called at end: 

Progress: <NSProgress: 0x1c413a540> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 2846305 of 2846305

**Comment by pappApproved** [comment]
I checked.
It's called after every chunk was uploaded. Regular chunk size is 5MB. 
It's 5242880. Your sample is lower then that (2846305) so it was uploaded all at once. It's proper behaviour.
Chunks can be smaller if you use intelligent ingestion. Then we start from 8MB, but if connection is weak we start splitting it into smaller parts.
