### ISSUE TITLE
FilestackSDK.MultipartUploadError.aborted

### ISSUE THREAD

**Issue by kaifucious** [filestack/filestack-swift#13]
Hello,

When uploading using the Filestack Swift SDK, I get a FilestackSDK.MultipartUploadError.aborted error, and I was just wondering what the underlying cause is (be it Filestack account specific, or just a generic upload error)

Thanks!

**Comment by sgerardi** [comment]
I'm having the same issue.  Is this SDK still getting support?

**Comment by sgerardi** [comment]
@kyuss Any updates on getting this issue resolved?

**Comment by sgerardi** [comment]
```
pod 'Filestack', '= 1.5.1'

post_install do |installer|
      installer.pods_project.targets.each do |target|
          if ['Filestack', 'FilestackSDK'].include? target.name
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.0'
              end
          end
      end
  end
```

**Comment by elropero** [comment]
Just to clarify, @sgerardi's snippet is a workaround; for me this issue occurred with pod FileStack v1.5.2 and Swift v4.2. 

Thanks @sgerardi

**Comment by kaifucious** [comment]
@sgerardi Is that solution still working on your end? I'm using Xcode 10/Swift 5 now and it seems to be broken again, same error.

**Comment by rnine** [comment]
@kaifucious, @sgerardi, @elropero: Sorry for late reply, but I am unable to replicate this issue using the latest FilestackSDK (v1.3.0) with Cocoapods (v1.5.3) and Xcode 10.2.1 on a fresh iOS app. I tried using Swift 4, 4.2 and 5 on this fresh app and I am not seeing any `FilestackSDK.MultipartUploadError.aborted` error.

Could you provide any more context on how to replicate this issue? It would be helpful to see what options were used when calling the `multiPartUpload()` function (e.g. store options, `useIntelligentIngestionIfAvailable` on/off, etc.)

Thanks!

**Comment by elropero** [comment]
It appears to have been fixed via https://github.com/filestack/filestack-swift/pull/12

**Comment by rnine** [comment]
@elropero OK, thanks! I'll close this.
