### ISSUE TITLE
Quick question of compressing

### ISSUE THREAD

**Issue by stardevrk** [filestack/filestack-swift#15]
I checked this Filestack-swift repo and Filestack-ios repo. I could see SSZipArchive framework in Filestack-ios repo, not in Filestack-swift. And when I use Filestack-ios, video was compressed.
So I just want to know if video is zipped or compressed when I use this Filestack-swift(FilestackSDK). 
Please let me know if it is right, or not.
Thanks.

**Comment by rnine** [comment]
@stardevrk `SSZipArchive` is currently only used to zip directories and bundles picked from documents (iOS Files) before uploading them to the storage location. 

Hope his helps!
