### ISSUE TITLE
Framework build with Carthage contains unnecessary files

### ISSUE THREAD

**Issue by divyeshmakwana96** [filestack/filestack-swift#17]
There are Carthage and cocoapod related files in the framework target
![Screen Shot 2020-01-21 at 11 41 44 AM](https://user-images.githubusercontent.com/10690686/72837375-3a7d7f80-3c43-11ea-80e7-9ed1352e01e3.png)

**Comment by rnine** [comment]
@sleekuser Thanks for reporting! Yes, I agree these files are completely unnecessary.
